//
// Created by Moad, Karl on 5/31/18.
//

#include "Utility.h"

const QString Utility::getDeviceId(QBluetoothDeviceInfo const &device) {

#ifdef Q_OS_MAC
    // On OS X and iOS we do not have addresses,
    // only unique UUIDs generated by Core Bluetooth.
    return device.deviceUuid().toString();
#else
    return device.address().toString();
#endif

}

QTreeWidgetItem* Utility::addTreeItem(QString const &name, QString const &value, QTreeWidget *tree, QTreeWidgetItem *parent) {

    QTreeWidgetItem *item;

    if(parent == nullptr) {
        item = new QTreeWidgetItem(tree);
        tree->addTopLevelItem(item);
    }
    else {

        item = new QTreeWidgetItem();
        parent->addChild(item);
    }

    item->setText(0, name);
    item->setText(1,value);

    return item;
}
